
services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    network_mode: "host"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cars
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

  adminer:
    image: adminer
    restart: always
    network_mode: "host"
